annotations:
  category: Database
apiVersion: v2
appVersion: 1.15.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Apache Geode is a data management platform that provides advanced capabilities for data-intensive applications.
home: https://github.com/bitnami/charts/tree/master/bitnami/geode
icon: https://bitnami.com/assets/stacks/geode/img/geode-stack-220x234.png
keywords:
  - apache
  - geode
  - database
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: geode
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/geode
  - https://github.com/apache/geode
version: 1.1.4
