annotations:
  category: MachineLearning
apiVersion: v2
appVersion: 3.0.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
engine: gotpl
home: https://jupyter.org/hub
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - python
  - scientific
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: jupyterhub
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/jupyterhub
  - https://github.com/jupyterhub/jupyterhub
version: 2.0.1
