# Multiple deployments pipelines are custom per asset. All single deployments pipelines are handled by ci-pipeline.yaml
name: '[CI/CD] CI Pipeline extra Thanos'
on: # rebuild any PRs and main branch changes
  pull_request_target:
    types:
      - reopened
      - synchronize
      - labeled
    branches:
      - master
    paths:
      - 'bitnami/thanos/*'
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-verify-bucketweb:
    # Given performance issues of the action feature on GH's side, we need to be very restrictive in the job's triggers:
    # -> The pipeline was triggered due to a label addition and said label was the 'verify' one OR
    # -> The pipeline was NOT triggered due to a label addition but the PR already contains the 'verify' one
    if: |
        github.event.action == 'labeled' && github.event.label.name == 'verify' ||
        github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'verify')
    runs-on: ubuntu-latest
    name: Verify BucketWeb on Tanzu Kubernetes Grid
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        with:
          pipeline: thanos/bucketweb/vib-verify.json
        env:
          VIB_ENV_TARGET_PLATFORM: ${{ secrets.VIB_ENV_TARGET_PLATFORM }}
